apiVersion: apps/v1
kind: Deployment
metadata:
  name: numbergame2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: numbergame2
  template:
    metadata:
      labels:
        app: numbergame2
    spec:
      containers:
      - name: numbergame2
        image: varimallamansa1/numbergame2:latest
        ports:
        - containerPort: 5000
