apiVersion: apps/v1
kind: Deployment
metadata:
  name: numbergame3-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: numbergame3
  template:
    metadata:
      labels:
        app: numbergame3
    spec:
      containers:
        - name: numbergame3
          image: varimallamansa1/numbergame3:latest
          ports:
            - containerPort: 5000
