apiVersion: v1
kind: Service
metadata:
  name: numbergame3-service
spec:
  type: NodePort
  selector:
    app: numbergame3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31111
